name: flutter_cleaner
description: help clean all of Flutter and Dart projects.
version: 1.0.3
homepage: https://github.com/fluttercandies/flutter_clean

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  flutter_clean: main
dependencies:
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0

# dart pub global activate --source path ./
